---
- name: Gestion Integral del Servidor
  hosts: all
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    # AHORA SOPORTA UNO O VARIOS (Separados por comas)
    - name: Levantar contenedores específicos
      docker_container:
        name: "{{ item | trim }}"
        state: started
      loop: "{{ contenedor_nombre.split(',') }}"
      when: 
        - accion == 'levantar'
        - contenedor_nombre | default('') | length > 0

    # EL RESTO SIGUE IGUAL
    - name: Obtener info de todos los contenedores
      docker_host_info:
        containers: yes
      register: docker_info
      when: accion == 'listar'

    - name: Mostrar lista
      debug:
        msg: "-> {{ item.Names[0] | replace('/', '') }} - {{ item.Status }}"
      loop: "{{ docker_info.containers | default([]) }}"
      when: accion == 'listar' and docker_info.containers is defined

    - name: Actualizar sistema
      apt:
        update_cache: yes
        upgrade: dist
      when: accion == 'actualizar'
