---
- name: Gestion Integral del Servidor
  hosts: all
  become: true
  tasks:

    # --- SECCIÓN DOCKER ---
    # ACCIÓN: LISTAR DOCKER
    - name: Obtener info de contenedores
      docker_host_info:
        containers: yes
      register: docker_info
      when: accion == 'listar'

    - name: Mostrar estado de los contenedores
      debug:
        msg: "Contenedor: {{ item.Names[0] | default('Sin nombre') }} - Estado: {{ item.Status | default('Desconocido') }}"
      loop: "{{ docker_info.containers }}"
      when: accion == 'listar' and docker_info.containers is defined

    # --- SECCIÓN ACTUALIZACIONES ---
    - name: Actualizar lista de paquetes (apt update)
      apt:
        update_cache: yes
      when: accion == 'actualizar'

    - name: Ejecutar actualización completa (apt upgrade)
      apt:
        upgrade: dist
      when: accion == 'actualizar'

    # --- SECCIÓN REINICIO ---
    - name: Reiniciar el servidor
      reboot:
      when: accion == 'reiniciar'
