---
- name: Tarea en mi servidor real
  hosts: all
  become: true
  tasks:
    - name: Crear un archivo de prueba
      copy:
        content: "Semaphore estuvo aquí"
        dest: /tmp/prueba_semaphore.txt

    - name: Tarea con reporte
      command: cat /tmp/prueba_semaphore.txt
      register: resultado_archivo

    - name: Mostrar el contenido en el log
      debug:
        msg: "El servidor dice: {{ resultado_archivo.stdout }}"
